//【自动生成侧边栏的模板】
/**
 * Creating a sidebar enables you to:（创建侧边栏使您能够：）
 - create an ordered group of docs（创建一个有序的文档组）
 - render a sidebar for each doc of that group（为该组的每个文档呈现一个侧边栏）
 - provide next/previous navigation（提供下一个/上一个导航）

 The sidebars can be generated from the filesystem, or explicitly defined here.（侧边栏可以从文件系统生成，或在此处明确定义。）

 Create as many sidebars as you want.（根据需要创建任意数量的侧边栏。）
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
